networks:
  app-network:
    driver: bridge

services:
  telegram-bot-service:
    build:
      context: .
      dockerfile: ./telegram-bot-service/Dockerfile
    env_file:
      - ./.env
    environment:
      SPRING_PROFILE_ACTIVE: prod
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      API_MAIN_UTILS_SERVICE_URL: ${API_UTILS_SERVICE_URL}
      #SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mydatabase
      #SPRING_DATASOURCE_USERNAME: myuser
      #SPRING_DATASOURCE_PASSWORD: mypassword
    # Другие настройки Spring Boot и JPA
    networks:
      - app-network
    depends_on: # Указывает зависимость от других сервисов (для порядка старта)
  #      database:
  #      condition: service_healthy # Или service_started
      main-utils-service:
          condition: service_started
  # healthcheck: # Настройте healthcheck для сервиса бота

  main-utils-service:
    build:
      context: .
      dockerfile: ./main-utils-service/Dockerfile
    env_file:
      - ./.env
    environment:
      JAVA_TOOL_OPTIONS: -Xms256m -Xmx1024m -XX:+UseContainerSupport
      SPRING_PROFILE_ACTIVE: prod
      EXTERNAL_AUDIO_API_URL: https://main-utils-service # URL внешнего API
      # Другие настройки
    networks:
      - app-network
    # healthcheck: # Настройте healthcheck для сервиса