version: "3.9"

networks:
  app-network:
    driver: bridge

services:

  telegram-bot-service:
    image: bunakdenis/telegram-bot-service:latest
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      USER_PASSWORD: ${PROD_USER_PASSWORD}
      TELEGRAM_BOT_NAME: ${PROD_TELEGRAM_BOT_NAME}
      TELEGRAM_BOT_TOKEN: ${PROD_TELEGRAM_BOT_TOKEN}
      API_USEFUL_TOOLS_URL: ${PROD_API_USEFUL_TOOLS_URL}
      API_USEFUL_TOOLS_FILE_SERVICE_ENDPOINT: ${PROD_API_USEFUL_TOOLS_FILE_SERVICE_ENDPOINT}
    networks:
      - app-network

  useful-tools:
    image: bunakdenis/useful-tools:latest
  #mem_limit: 12g
    env_file:
      - ./.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      USER_PASSWORD: ${PROD_USER_PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "$${PROD_API_USEFUL_TOOLS_URL}:$${PORT}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - ${PORT}:8080