name: CI & Deploy to Railway
on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push telegram-bot-service image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./telegram-bot-service/Dockerfile
          push: true
          tags: ghcr.io/bunakdenis/telegram-bot-service:latest
          load: false
          no-cache: false
          pull: true

      - name: Build and push main-utils-service image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./main-utils-service/Dockerfile
          push: true
          tags: ghcr.io/bunakdenis/main-utils-service:latest
          load: false
          no-cache: false
          pull: true

  deploy-railway:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g railway

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --apiKey $RAILWAY_TOKEN

      - name: Link Project
        env:
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: railway link $RAILWAY_PROJECT_ID

      - name: Deploy telegram-bot-service
        env:
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME_TELEGRAM }}
          SPRING_PROFILES_ACTIVE: prod
          PROD_TELEGRAM_BOT_TOKEN: ${{ secrets.PROD_TELEGRAM_BOT_TOKEN }}
        run: |
          railway up --detach \
            --service $RAILWAY_SERVICE_NAME \
            --image ghcr.io/${{ github.repository_owner }}/telegram-bot-service:latest \
            --env SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE \
            --env TELEGRAM_BOT_TOKEN=$PROD_TELEGRAM_BOT_TOKEN

      - name: Deploy main-utils-service
        env:
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME_UTILS }}
          SPRING_PROFILES_ACTIVE: prod
        run: |
          railway up --detach \
            --service $RAILWAY_SERVICE_NAME \
            --image ghcr.io/${{ github.repository_owner }}/main-utils-service:latest \
            --env SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE