name: CI
on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Сборка и пуш образа telegram-bot-service
      - name: Build & push telegram-bot-service image
        run: mvn -pl telegram-bot-service compile jib:build \
          -Dimage=ghcr.io/bunakdenis/telegram-bot-service:latest

      # Сборка и пуш образа useful-tools
      - name: Build & push useful-tools image
        run: mvn -pl useful-tools compile jib:build \
          -Dimage=ghcr.io/bunakdenis/useful-tools:latest