name: CI & Deploy to Railway
on:
  push:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push telegram-bot-service image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./telegram-bot-service/Dockerfile
          push: true
          tags: ghcr.io/bunakdenis/telegram-bot-service:latest
          load: false
          no-cache: false
          pull: true

      - name: Build and push main-utils-service image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./main-utils-service/Dockerfile
          push: true
          tags: ghcr.io/bunakdenis/main-utils-service:latest
          load: false
          no-cache: false
          pull: true